### PR TITLE
quicklogic: add toolchain install test

### PR DESCRIPTION
**Pull request by acomodi**
This PR fixes https://github.com/QuickLogic-Corp/symbiflow-arch-defs/issues/270.

It adds a test to verify that the installed toolchain is not erroring out, and is properly working.

### CODE REVIEW

**Comment by kkumar23** [comment]
@acomodi : so any new testcase if i need to add, i should also add in the build.yml ?

**Comment by acomodi** [comment]
@kkumar23 So, if you want to use the same design and the same device you may enhance the Makefile in the `install_test` directory. This can be done in case more features need to be tested.

In general, though, the toolchain installation checks should only regard the feature testing (e.g. liberty file generation, post synthesis checks, etc.). In case a new design needs to be tested, it is better to add it to the test suite as all the other tests.

**Review by kkumar23 — COMMENTED** [review]
ok, got it. json file is not required now, as the support for the clk's is now present in the pcf file.

**Comment by acomodi** [comment]
>  json file is not required now, as the support for the clk's is now present in the pcf file.

Ok, I have removed it

**Pull request merged**
