### PR TITLE
Switch to litex-hub conda channel and fix tests

### PR DESCRIPTION
**Pull request by kgugala**
#186 changed ASSP clock names, however Yosys in QL channel was not bumped, so synthesis of some test designs fails with:

```
ERROR: Module `qlal4s3b_cell_macro' referenced in module `top' in cell `u_qlal4s3b_cell_macro' does not have a port named 'Clk21_Rst'
```
This PR switches conda channel to litex-hub and updates the packages so they include the latest changes.

Also, some tests outside the test_suite directroty were updated to use new ASSP clock names

### CODE REVIEW

**Comment by kgugala** [comment]
Let's wait for CI to see if the issues are fixed

**Comment by kgugala** [comment]
I have dropped travis CI configuration - it was suppose to run the exact same tests as gh-actions (but in reality it was stalling the our PRs). Removing it will not really degrade test coverage.

**Comment by kgugala** [comment]
CI is green. @tpagarani @lnsharma @kkumar23 if it's OK for you to switch to litex-hub conda channel and drop travis we can merge this one

**Comment by tpagarani** [comment]
I am ok with the proposed changes.

**Pull request merged**
