### PR TITLE
git-lfs support

### PR DESCRIPTION
**Pull request by kkumar23**

### CODE REVIEW

**Comment by kkumar23** [comment]
Currently user needs to have git-lfs installed locally.

**Comment by mkurc-ant** [comment]
@kkumar23 The change looks good. But keep in mind that we won't be able to upstream it to SymbiFlow as we cannot use `git-lfs` there.

**Comment by kkumar23** [comment]
@mkurc-ant Well in that case need to explore other options, meanwhile this will be a temporary fix.

**Comment by kkumar23** [comment]
@mkurc-ant : With this option it installs the git-lfs. But when we run any design it does not identify the git-lfs for the repo.

gzip: /home/kkumar23/DD_0906/symbiflow-arch-defs/build/quicklogic/qlf_k6n10/devices/gf12/qlf_k6n10-qlf_k6n10_gf12.rr_graph.bin.gz: not in gzip format

**Comment by mkurc-ant** [comment]
@kkumar23 From what I know one needs to manually do `git lfs pull` inside the `qlfpga_symbiflow_plugins` submodule directory after the submodule has been initialized.

I've found that supposedly when one clones the SymbiFlow repository for the first time one may do it using `git clone --recurse-submodules`. This should automatically do lfs pulls on submodules.

**Pull request merged**
