### PR TITLE
WIP: test all ql target

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

### CODE REVIEW

**Comment by kkumar23** [comment]
@acomodi : Travis is red with this merge

**Comment by acomodi** [comment]
@kkumar23 yes, this because the all_ql_tests are now enabled. One of the first issues to solve is the following

```
/dev/stdin < /home/travis/build/QuickLogic-Corp/symbiflow-arch-defs/build/quicklogic/pp3/devices/ql-pp3e-virt/arch.unique_pack.xml > arch.timing.xml
Traceback (most recent call last):
  File "/home/travis/build/QuickLogic-Corp/symbiflow-arch-defs/utils/update_arch_timings.py", line 297, in <module>
    main()
  File "/home/travis/build/QuickLogic-Corp/symbiflow-arch-defs/utils/update_arch_timings.py", line 290, in main
    th.attrib['value'] = th.attrib['value'].format(**bel_timings)
KeyError: 'hold_QCK_QDI'
```

This is due to the fact that the SDF does not have the HOLD timing for the QCK to QDI connection. The liberty files do set that particualr timing to zero and it gets skipped. There is a fix for this here: https://github.com/QuickLogic-Corp/quicklogic-timings-importer/pull/2.

**Comment by acomodi** [comment]
The next error that popped up in CI is the following:

```
vpr/src/base/read_netlist.cpp:1079 mark_constant_generators_rec: Assertion 'atom_ctx.nlist.pin_is_constant(driver_pin_id)' failed.
```

This might be due to a synthesis issue as it affects the netlist reading step and it is related to the constant nets

**Comment by kkumar23** [comment]
@acomodi : Is this pull request ready. By mistake i marked this as ready.

**Comment by acomodi** [comment]
>  Is this pull request ready

@kkumar23 Not yet actually, I think it would be best to have CI always be green before merging on the current main branch, as it gets easier to track down regressions.

There are two outstanding issues with the `all_ql_tests` which are described here: https://github.com/QuickLogic-Corp/symbiflow-arch-defs/issues/97#issuecomment-673560981.

If we want to enable the all_ql_tests ASAP we might consider to temporarily disable the failing tests and open issues to solve those and re-enable the tests in a second step. What do you think?

**Comment by kkumar23** [comment]
@acomodi : If these are 2-3 testcases, then we can open a new PR for them and disable meanwhile. 
One more thing we observed was that few testcases started failing from 11th Aug, after few merges. 
These testcases fail during packer run. 
quicklogic/pp3/tests/counter
quicklogic/pp3/tests/ram
quicklogic/pp3/tests/soc_clocks
quicklogic/pp3/tests/sdiomux_counter
I assume these are related to the same https://github.com/QuickLogic-Corp/symbiflow-arch-defs/issues/97#issuecomment-673560981

**Comment by acomodi** [comment]
@kkumar23 Indeed, I have identified the issue with those failing tests that do trigger the VTR assertion. Working on a fix now.

**Comment by acomodi** [comment]
This PR now takes more than an hour to complete and Travis is killed. This because of the amount of tests to build which are too many w.r.t. Travis capabilities. 

Probably the basic tests should all be added to the all_quick_tests and leave the more complex designs out of travis CI check for now.

**Pull request merged**
