### PR TITLE
cmake: fix dependencies so that make with multi jobs can be used

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

Fixes https://github.com/QuickLogic-Corp/symbiflow-arch-defs/issues/171

### CODE REVIEW

**Review by kgugala — APPROVED** [review]
LGTM

**Comment by kgugala** [comment]
@acomodi since #174 is merged, can we rebase this PR so it gets tested in GH actions?

**Comment by acomodi** [comment]
@kgugala Sure, makes sense

**Comment by acomodi** [comment]
I have reverted back CI to use `make` instead of `ninja` (as make is more unstable) so that it gets tested in CI.

**Comment by kgugala** [comment]
as expected GH actions passed, travis timed out. I think we can remove travis from this repo, or use it just for quick checks (like e.g. code formatting)

**Comment by kkumar23** [comment]
We can keep the Travis.

**Review by kkumar23 — APPROVED** [review]

**Comment by kkumar23** [comment]
@kgugala : for email notification's on the build status , do we need to set anything for GH actions ?

**Comment by kgugala** [comment]
By default, the notifications are sent to the author of the commit which triggered the build

**Pull request merged**
