### PR TITLE
Testcase set3

### PR DESCRIPTION
**Pull request by kkumar23**

### CODE REVIEW

**Comment by kkumar23** [comment]
@acomodi : i see that the testcases at :quicklogic/qlf_k4n8/tests/features
io_max
io_reg_max
shift_reg_4098   
fail in CI, but when run locally they pass. I could not figure out the reason.

**Comment by acomodi** [comment]
Hi @kkumar23, I am looking at this, but in general, comparing an output that is non-deterministic, unless it is run on the same exact machine with the same exact inputs, may yield unexpected results, and behaviour you are seeing.

I can see CI is failing at the stage where it verifies the output in the route file. I think this is not a safe test to perform to verify the goodness of the results.

On a side note, I see a bitstream being checked in. This is something to avoid, and all generated files should not be part of the codebase.

**Comment by kkumar23** [comment]
> Hi @kkumar23, I am looking at this, but in general, comparing an output that is non-deterministic, unless it is run on the same exact machine with the same exact inputs, may yield unexpected results, and behaviour you are seeing.
> 
> I can see CI is failing at the stage where it verifies the output in the route file. I think this is not a safe test to perform to verify the goodness of the results.
> 
> On a side note, I see a bitstream being checked in. This is something to avoid, and all generated files should not be part of the codebase.
    : Removed this file

Well, we are extracting the data from the file being generated like route.log/place.log etc. The data like clk frequency/utilization should match. Be it any system. The whole purpose is to have the same data generated across system.
Fir eg: if a design uses 1000FF's , it cannot change if we run on other system.

**Comment by acomodi** [comment]
> The data like clk frequency/utilization should match. Be it any system.

Surely the results should be in a close range between one system to the other (specifically the frequency results), but we cannot have an exact match between to runs on different systems, given the non-determinism of place and route tools.

Besides this, the problem I see is that, upon upgrading the versions of the tools, these results will most probably change, and it would require adapting the tests

**Comment by acomodi** [comment]
As an example, by running this changes locally, I get the following frequency for the `dct_mac_test3`:

```
Final critical path delay (least slack): 25.923 ns, Fmax: 38.5758 MHz
```

This yields an error, as it is out of the range specified, while using the same VPR and yosys versions specified in the `environment.yml`.

**Comment by kkumar23** [comment]
> > The data like clk frequency/utilization should match. Be it any system.
> 
> Surely the results should be in a close range between one system to the other (specifically the frequency results), but we cannot have an exact match between to runs on different systems, given the non-determinism of place and route tools.
> 
> Besides this, the problem I see is that, upon upgrading the versions of the tools, these results will most probably change, and it would require adapting the tests

Yes for that i have put range of +/-10% for the clk. But for FF's it should not change.  Are the testcases failing because of this ? or is there some other issue.

**Comment by acomodi** [comment]
>  Are the testcases failing because of this ?

Yes, locally on my machine, what is failing is the clk_verify target.

**Comment by kkumar23** [comment]
@acomodi : i have extended the range and CI is now green. We are adding these unit-testcases just to check if there are no Major variation in the frequency or utilization.

**Comment by acomodi** [comment]
@kkumar23 Ok, I think that, if possible, a range also for the resources utilization might be required as well (to cover the case in which a tool's version is updated and yields different results)

**Comment by kkumar23** [comment]
Well for the IO and FF resources ideally should not change with tools version. It should definitely be flagged. 
You think they can still change ?

**Comment by acomodi** [comment]
Hmm right, if those are IOs than they should not change.

**Pull request merged**
