### PR TITLE
Use Cached Lookahead

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

This PR is to add the cached lookahead. By using with the QuickLogic flow, I have seen the lookahead generation overhead which can be simply reduced to zero if we use the cached lookahead.

This should automatically apply to the install package as well.

### CODE REVIEW

**Comment by acomodi** [comment]
There seems to be an error in CI related to the architecture specifications:

```
Error 1: /home/travis/build/QuickLogic-Corp/symbiflow-arch-defs/build/quicklogic/pp3/devices/ql-eos-s3-virt/arch.timing.xml:-1 <pb_type> 'MULT' timing-annotation/<model> mismatch on port 'sel_mul_32x32' of model 'MULT', input port 'sel_mul_32x32' has combinational connections to port 'Cmult'; specified in model, but no combinational delays found on pb_type
The entire flow of VPR took 0.12 seconds (max_rss 18.2 MiB)
```

The MULT pb_type seems not to be missing constant delay values.

**Comment by kkumar23** [comment]
@acomodi : Below error is now Fixed.
Error 1: /home/travis/build/QuickLogic-Corp/symbiflow-arch-defs/build/quicklogic/pp3/devices/ql-eos-s3-virt/arch.timing.xml:-1 <pb_type> 'MULT' timing-annotation/<model> mismatch on port 'sel_mul_32x32' of model 'MULT', input port 'sel_mul_32x32' has combinational connections to port 'Cmult'; specified in model, but no combinational delays found on pb_type
The entire flow of VPR took 0.12 seconds (max_rss 18.2 MiB)

**Comment by acomodi** [comment]
@kkumar23 All right, I have added the lookahead for the routing step to be cached so that it does not need to get recomputed every time both the placement and the routing steps are performed. This saves ~17 seconds for EOS three of overhead for each P&R step.

Also, I have reduced the warning output, so that CI should be now able to not fail due to exceeded length of the std output.

**Comment by acomodi** [comment]
Now I get the same error in CI as in master. It is related to https://github.com/QuickLogic-Corp/symbiflow-arch-defs/issues/103.

I believe the latest QMUX changes are the cause (https://github.com/QuickLogic-Corp/symbiflow-arch-defs/pull/102) as they may affect the fasm2bels step.
I believe that we should get CI to go green by temporarily disabling the failing fasm2bels tests, so that, in the future, only green PRs get merged, and we can avoid having regressions.

**Comment by kkumar23** [comment]
@acomodi : My commit https://github.com/QuickLogic-Corp/symbiflow-arch-defs/commit/0977a181670670c941921e1e8f121d4a253a99e8 , has selected tests which does not fail on fasm2bels step. Not sure why spi_master_top testcase is running even though it does not have the all_quick_tests target !

**Pull request merged**
