### PR TITLE
Fix issues in this repo for k4n8 and k6n10

### PR DESCRIPTION
**Pull request by coolbreeze413**
- correct exit codes to be non-zero when make steps fail in ql_symbiflow wrapper, like at: https://github.com/QuickLogic-Corp/symbiflow-arch-defs/blob/54803801d8f94a79f7b5c7b9ffa284a83182f5a2/quicklogic/common/toolchain_wrappers/ql_symbiflow#L568

- correct error in usage of `[` in bash if we use `&&` in https://github.com/QuickLogic-Corp/symbiflow-arch-defs/blob/54803801d8f94a79f7b5c7b9ffa284a83182f5a2/quicklogic/common/toolchain_wrappers/ql_symbiflow#L266

- minor aesthetic change in generated Makefile.symbiflow

This is a WIP, and more changes might be needed after testing.

### CODE REVIEW

**Comment by coolbreeze413** [comment]
@mkurc-ant @kgugala : The CI failures with the eos-s3 may be valid failures, as the previously, the ql_symbiflow wrapper would not return a non-zero exit value even if any make step failed.
This PR fixes that, and hence the failures in CI may be visible now.

Please review and check if this is the case, or if there is anything in the PR that is causing real CI failures.

**Comment by coolbreeze413** [comment]
@mkurc-ant @kgugala : This seems to be a valid error, and it was being masked due to the zero return value from the ql_symbiflow wrapper.

The latest commit merged on the master also shows the errors: https://github.com/QuickLogic-Corp/symbiflow-arch-defs/runs/4379018876?check_suite_focus=true#step:6:61

**Comment by mkurc-ant** [comment]
@coolbreeze413 You are right. I have examined the logs and I can see two issues which probably have been masked out by the zero return value:

In installed toolchain tests during fasm2bels stage. Probably there is some inconsistency in the wrapper scripts when it comes to specifying a package for PP3 and a pinmap for k4n8:
```
2021-12-05T21:46:30.3075350Z 6: Running fasm2bels
2021-12-05T21:46:30.3075749Z 6: Traceback (most recent call last):
2021-12-05T21:46:30.3077047Z 6:   File "/home/runner/work/symbiflow-arch-defs/symbiflow-arch-defs/quicklogic-arch-defs/bin/python/fasm2bels.py", line 1107, in <module>
2021-12-05T21:46:30.3078451Z 6:     f2b = Fasm2Bels(db, args.device_name, args.package_name)
2021-12-05T21:46:30.3080347Z 6:   File "/home/runner/work/symbiflow-arch-defs/symbiflow-arch-defs/quicklogic-arch-defs/bin/python/fasm2bels.py", line 72, in __init__
2021-12-05T21:46:30.3081490Z 6:     ", ".join(db["package_pinmaps"].keys())
2021-12-05T21:46:30.3082813Z 6: __main__.Fasm2BelsException: ERROR: 'chandalar_pinmap.csv' is not a vaild package for device 'eos-s3'. Valid ones are: WR42, PD64, PU64
```

And in the CMake script which runs the toolchain tests:
```
2021-12-01T10:46:05.5915486Z 14: CMake Warning (dev) at /home/runner/work/symbiflow-arch-defs/symbiflow-arch-defs/quicklogic/common/cmake/run_toolchain_test.cmake:76 (SET):
2021-12-01T10:46:05.5916347Z 14:   Syntax error in cmake code at
2021-12-01T10:46:05.5916700Z 14: 
2021-12-01T10:46:05.5917613Z 14:     /home/runner/work/symbiflow-arch-defs/symbiflow-arch-defs/quicklogic/common/cmake/run_toolchain_test.cmake:76
2021-12-01T10:46:05.5918322Z 14: 
2021-12-01T10:46:05.5918654Z 14:   when parsing string
2021-12-01T10:46:05.5918971Z 14: 
2021-12-01T10:46:05.5919682Z 14:     \\\S*\[[0-9]*\]\s
2021-12-01T10:46:05.5919973Z 14: 
2021-12-01T10:46:05.5920337Z 14:   Invalid escape sequence \S
2021-12-01T10:46:05.5920708Z 14: 
2021-12-01T10:46:05.5921213Z 14:   Policy CMP0010 is not set: Bad variable reference syntax is an error.  Run
2021-12-01T10:46:05.5922113Z 14:   "cmake --help-policy CMP0010" for policy details.  Use the cmake_policy
2021-12-01T10:46:05.5922778Z 14:   command to set the policy and suppress this warning.
2021-12-01T10:46:05.5923662Z 14: This warning is for project developers.  Use -Wno-dev to suppress it.
```
Let us work on fixing those.

**Comment by coolbreeze413** [comment]
@mkurc-ant Thanks!

I have merged the master and updated the PR.

The final changes done are:

- correct exit codes to be non-zero when make steps fail in ql_symbiflow wrapper, like at: https://github.com/QuickLogic-Corp/symbiflow-arch-defs/blob/54803801d8f94a79f7b5c7b9ffa284a83182f5a2/quicklogic/common/toolchain_wrappers/ql_symbiflow#L568

- correct error in usage of `[` in bash if we use `&&` in https://github.com/QuickLogic-Corp/symbiflow-arch-defs/blob/54803801d8f94a79f7b5c7b9ffa284a83182f5a2/quicklogic/common/toolchain_wrappers/ql_symbiflow#L266

- correct checking expansion of `*.v` so that it doesn't throw an error if `*.v` is already expanded correctly at https://github.com/QuickLogic-Corp/symbiflow-arch-defs/blob/4acf609042f3b71c686a988440d926ed32e92d82/quicklogic/common/toolchain_wrappers/ql_symbiflow#L230

- add explicit exit codes to all exit statements

- minor aesthetic change in generated Makefile.symbiflow

Please review the final changes, if they look ok, we can merge them now, so that the latest arch-defs can be used for automated testing with correct exit codes.
We can debug the issues in the eos-s3 CI in parallel.
What do you think?

**Comment by mkurc-ant** [comment]
@coolbreeze413 I've managed to narrow down the issue with CI (I hope) See the linked PR.

**Comment by coolbreeze413** [comment]
@mkurc-ant Thanks! I think it looks good.

Let's wait for the CI in #711 to complete, and if it is green, merge that first, and then I will update this PR for remaining changes, and we can merge this next.

**Comment by coolbreeze413** [comment]
merged #711, and merged master here.

Final remaining changes in this PR:

The final changes done are:

- correct error in usage of `[` in bash if we use `&&` in https://github.com/QuickLogic-Corp/symbiflow-arch-defs/blob/54803801d8f94a79f7b5c7b9ffa284a83182f5a2/quicklogic/common/toolchain_wrappers/ql_symbiflow#L266

- correct checking expansion of `*.v` so that it doesn't throw an error if `*.v` is already expanded correctly at https://github.com/QuickLogic-Corp/symbiflow-arch-defs/blob/4acf609042f3b71c686a988440d926ed32e92d82/quicklogic/common/toolchain_wrappers/ql_symbiflow#L230

- add explicit exit codes to all exit statements

- minor aesthetic change in generated Makefile.symbiflow

**Comment by coolbreeze413** [comment]
@mkurc-ant : This PR is now green, and the remaining changes in the PR are simple ones.
Please review, and if ok, we can merge this one as well.

**Review by mkurc-ant — APPROVED** [review]
Alright. Looks good.

**Pull request merged**
