### PR TITLE
Add header, binary, jlink, openocd support for eoss3

### PR DESCRIPTION
**Pull request by coolbreeze413**
This PR adds the missing support from latest Symbiflow package to generate additional formats for the EOS-S3 bitstream:
- Binary (flashable binary format)
- JLink script
- OpenOCD script
- C Header

The toolchain wrappers are rewritten to directly invoke the quicklogic-fasm package modules, so that must be installed for using this functionality, which is anyway required to be used for EOS-S3.

**[minor]** In addition, it also fixes an error in usage of `[` in bash if we use `&&` in https://github.com/QuickLogic-Corp/symbiflow-arch-defs/blob/54803801d8f94a79f7b5c7b9ffa284a83182f5a2/quicklogic/common/toolchain_wrappers/ql_symbiflow#L266

### CODE REVIEW

**Comment by coolbreeze413** [comment]
Reverted the k4n8/k6n10 related correction, as there are more lines to change.
Will create a separate PR for k4n8/k6n10 related changes so that it will be cleaner.

**Comment by coolbreeze413** [comment]
created separate PR #709 for k4n8/k6n10 related changes.

**Review by mkurc-ant — APPROVED** [review]
Ok, looks good.

**Comment by coolbreeze413** [comment]
@mkurc-ant Thanks! I will merge the PR.

**Pull request merged**
