### PR TITLE
quicklogic: toolchain tests: add simulation tests as well

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

This PR adds a simulation step to the toolchain tests.

The test requires a testbench, and the DUT is taken from the post-layout netlist, output by VPR

It still requires the simulation for the fasm2bels output, therefore it is marked as WIP

### CODE REVIEW

**Comment by lpawelcz** [comment]
I temporary disabled the installed toolchain simulation tests for EOS-S3 counter design because of possible faulty SDF generation for the EOS-S3 that was breaking the simulation. Using SDF from PP3 flow fixes the simulation so that the counter states in particular moments of the simulation are correct.

**Comment by lpawelcz** [comment]
Summary of changes:
* Added CMake infrastructure for performing 3 simulation test cases: post-VPR with split ports, post-VPR with merged ports, post-fasm2bels
* Enabled simulation tests for designs: `lut{1, 2, 3, 4}`, `counter`
* Fixed typos in `cells_map.v`
* Included `LOGIC_MACRO` primitive in `cells_sim.v` generation to enable post-VPR simulation
* Introduced to CMake flow and installed toolchain a `cells_sim.v` file taken from yosys (added to symbiflow under name `yosys_cells_sim.v` that is required for post-fasm2bels simulation
* Create build directory and test names based on the pinmap and device of particular test case to avoid naming conflicts and duplicating test sources
* slightly increased usage limit of `PB_LOGIC` blocks for 2 test cases
* Fixed regex that was picking for merging only very specific module port names instead of all that are necessary
* Fixed lack of PCF files in EOS-S3 tests
* Disabled EOS-S3 test for counter as explained in previous comment

**Comment by lpawelcz** [comment]
@tpagarani and @coolbreeze413 please have a look at this. It is ready for review.

**Review by tpagarani — APPROVED** [review]
LGTM

**Pull request merged**
