### PR TITLE
PP3 tests

### PR DESCRIPTION
**Pull request by mkurc-ant**
This PR adds most of the tests from `quicklogic/designs` for the PP3 device.

Some test designs were not added because they are either too big to fit into the fabric or require too many IOs. Simple tests (like `and2`) were skipped as they do not bring in any more new coverage of tested features.

This PR also fixes an issue with clock placement constraints generation for the PP3 family plus solves one dependency issue in CMake scripts.

### CODE REVIEW

**Comment by mkurc-ant** [comment]
Requires https://github.com/QuickLogic-Corp/symbiflow-arch-defs/pull/537 for the CI to pass.

**Review by lnsharma — APPROVED** [review]
LGTM

**Comment by tpagarani** [comment]
@lnsharma @mkurc-ant this is causing CI to fail

**Comment by mkurc-ant** [comment]
@tpagarani 
This is strange as the CI passed for this PR. It looks like there is a segfault in ABC9 for the `bin2seven` design:
```
4.50.17.5. Executing ABC9.
ERROR: ABC: execution of command "/home/runner/work/symbiflow-arch-defs/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/yosys-abc -s -f /tmp/yosys-abc-jBGFj3/abc.script 2>&1" failed: return code 134.
```

I'll investigate what is happening.

**Pull request merged**
