### PR TITLE
Fix for fasm2bels behavior for bitstreams with default mux configuration

### PR DESCRIPTION
**Pull request by mkurc-ant**
This PR fixes `fasm2bels` plus adds targets that invoke it to the GitHub CI.

### CODE REVIEW

**Review by kkumar23 — APPROVED** [review]
looks fine.

**Review by lnsharma — APPROVED** [review]
Looks good

**Review by kkumar23 — APPROVED** [review]
Ok you have added new target bit_v.

**Comment by kkumar23** [comment]
@mkurc-ant  The CI is failing, so cannot merge

**Comment by mkurc-ant** [comment]
@kkumar23 It looks like the failure is caused by the change of names of `qlal4s3b_cell_macro` cell ports. Can you provide the final naming for this ports so that I can check whether everything is consistent between Yosys and SymbiFlow ?
```
ERROR: Module `qlal4s3b_cell_macro' referenced in module `top' in cell `u_qlal4s3b_cell_macro' does not have a port named 'Clk_C16'.
```

**Comment by kkumar23** [comment]
@mkurc-ant : The ports Sys_Clk0 is now changed to Clk_C16 and Sys_Clk1 to Clk_C21

**Comment by mkurc-ant** [comment]
@kkumar23 So the reason for the PR failure is that the port names got updated in the VPR arch but not in Yosys - at least not in the version installed in the Conda environment.

This fork of symbiflow-arch-defs installs `quicklogic-yosys v0.8.0_75_g3609a7d9 20210127_093658`. This is specified in the master `CMakeLists.txt`:
https://github.com/QuickLogic-Corp/symbiflow-arch-defs/blob/f9257d0595760ceef008d38cfed668b8315f8f0b/CMakeLists.txt#L38
This Yosys version names the ports differently:
https://github.com/QuickLogic-Corp/yosys/blob/3609a7d913446ec9a2dde1fd19173bade793aa58/techlibs/quicklogic/pp3_cells_sim.v#L2040-L2043

So the solution is to build a new conda package with Yosys version that has the ports named correctly. Since this package is built on your side I'd like to ask you to do it. Then I can update the version in `CMakeLists.txt` once it is ready. After that the CI should go green (provided that there are no other unrelated issued).

**Comment by kkumar23** [comment]
@mkurc-ant : The packages are now taken from the litex-hub channel. Karol has changed (https://github.com/QuickLogic-Corp/symbiflow-arch-defs/pull/188/commits/403c27e66801dd2e54bfedfb3c7cf482431633ae) .  So you can pick the latest from the litex hub.

**Comment by mkurc-ant** [comment]
@kkumar23 Ok, I'll update the package in a minute

**Comment by kkumar23** [comment]
@mkurc-ant : still tests failing:
quicklogic/pp3/tests/counter/CMakeFiles/file_quicklogic_pp3_tests_counter_counter-ql-quickfeather_ql-s3-ql-eos-s3-virt-ql-eos-s3-wlcsp_top_bit.v.dir/build.make:80: recipe for target 'quicklogic/pp3/tests/counter/counter-ql-quickfeather/ql-s3-ql-eos-s3-virt-ql-eos-s3-wlcsp/top_bit.v' failed

**Comment by mkurc-ant** [comment]
@kkumar23 Right. I see that there are more issues besides those I've fixed. I'm working on it...

**Comment by mkurc-ant** [comment]
@kkumar23 I've fixed all the issues. The CI is green now.

**Review by kkumar23 — APPROVED** [review]

**Pull request merged**
