### PR TITLE
Add qlf_k6n10 to installed toolchain package

### PR DESCRIPTION
**Pull request by mkurc-ant**
This PR fixes a number of things for `qlf_k6n10` to be included in installed toolchain package:
 - Moved common utils out of `qlf_k4n8/utils` to `common/utils`
 - Unified installed toolchain testing framework
 - Added installation of files for `qlf_k6n10` architecture
 - Added a test for installed toolchain with `qlf_k6n10` that is run by CI

Packages that are uploaded by CI from this PR and later from master when its merged will contain `qlf_k6n10` support.

### CODE REVIEW

**Comment by kkumar23** [comment]
@mkurc-ant : I see latest package uploaded to bucket does "not" have the k6n10 files.

https://console.cloud.google.com/storage/browser/symbiflow-arch-defs-install;tab=objects?forceOnBucketsSortingFiltering=false&project=conda-package-builder-ci&prefix=&forceOnObjectsSortingFiltering=true&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%257B_22k_22_3A_22Name%2520prefix_22_2C_22t_22_3A17_2C_22v_22_3A_22_5C_22quicklogic-arch-defs-qlf_5C_22_22_2C_22i_22_3A_22displayName_22%257D%255D%22,%22s%22:%5B(%22i%22:%22objectListDisplayFields%2FtimeCreated%22,%22s%22:%221%22),(%22i%22:%22displayName%22,%22s%22:%220%22)%5D))&pli=1

**Comment by mkurc-ant** [comment]
@kkumar23 Ok, I've made a typo. let me fix that.

**Comment by kkumar23** [comment]
@mkurc-ant : CI is red.

**Comment by mkurc-ant** [comment]
@kkumar23 I see issues with repacking. I've noticed that previously the repacker was disabled for `qkf_k6n10`. I enabled it and now I see that it fails. Shall I disable it again both for CMake and installed toolchain flow? Or shall I keep it enabled and start working on fixing the failure?

**Comment by kkumar23** [comment]
@mkurc-ant : we need to keep common PnR options for both the devices, so its better we fix the repacker issue for k6n10.

**Comment by kkumar23** [comment]
@mkurc-ant : As Tara mentioned we do not need repacker for the k6n10 now. We disable it in both for CMake and installed toolchain flow.

**Comment by mkurc-ant** [comment]
@kkumar23 Ok, Let me do the relevant changes.

**Comment by mkurc-ant** [comment]
@kkumar23 CI is green, the package should be uploaded and should contain qlf_k6n10 files.

**Pull request merged**
