### PR TITLE
Repacker constraints in CMake

### PR DESCRIPTION
**Pull request by mkurc-ant**
This PR allows to specify repacking constraints for each design in the CMake build system. It also adds an example of how it should be done.

### CODE REVIEW

**Comment by kkumar23** [comment]
@mkurc-ant Json file is temporary i believe, later we will add in the pcf file.  There are merge conflicts.

**Comment by mkurc-ant** [comment]
@kkumar23 Indeed its temporary. I'm adding it now as you asked: https://github.com/QuickLogic-Corp/symbiflow-arch-defs/issues/235#issuecomment-831906957 We will be working on supporting the constraints via PCF.

Meanwhile I see that you have removed all the tests from `quicklogic/qlf_k4n8/tests` and in this PR I've added one new test there - that is why there is a conflict. Can you point me out to where the tests are now?

**Comment by kkumar23** [comment]
@mkurc-ant : I have moved all except counter design . You can add parallel to that.

**Review by kkumar23 — APPROVED** [review]
Looks good

**Pull request merged**
