### PR TITLE
Fixed command-line option file lookup

### PR DESCRIPTION
**Pull request by mkurc-ant**
This PR fixes lookup of command-line option files specified via the `-f` switch.

### CODE REVIEW

**Comment by kkumar23** [comment]
@mkurc-ant : after we updated the yosys-plugins into the environment.yml, the testcases runtime increased from 2 hrs to more than 6hrs and they are now getting auto cancelled. Even CI for this PR shows red because of this.
Is there option to check run-time of each testcase in the github action log?

**Review by kkumar23 — COMMENTED** [review]
LGTM

**Review by lnsharma — APPROVED** [review]
looks fine.

**Comment by mkurc-ant** [comment]
@kkumar23 I've noticed the time increase too. It probably also has to do with rr graph lookahead map computation for k6n10 - its much bigger than k4n8.

There is no total time spent on each test written to the main log. However times for individual stages like synthesis, pack, place route are outputted by Yosys and VPR. Unfortunately those logs are not preserved in CI.

One immediately available solution would be to run all the tests locally and then examine the individual log files for reported runtime and remove the long-running tests from CI

**Pull request merged**
